name: _data_layer
description: Data Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  flutter:
    sdk: flutter
  objectbox: ^1.5.0
  objectbox_flutter_libs: ^1.5.0
  path_provider: ^2.0.10
  riverpod: any

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  objectbox_generator: ^1.5.0
      
flutter:
